### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by dabsolutions** [dabsolutions/slack-invite-automation#1]
Change the background to include the Dab Solutions Logo

Also change the color/design

**Comment by scottgrayson** [comment]
do you want to use the same background as the dabsolutions site?
![image](https://user-images.githubusercontent.com/7796074/35472976-0bd9091a-0347-11e8-8088-f65685f89a50.png)

**Comment by xRobeSx** [comment]
Yea man that works great, I didn’t have anything in mind
